title:               Steadier Footing
url:                 https://sarmadsiddiqui.github.io/steadierfooting/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /page/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Sarmad Siddiqui
  url:               
  email:             sarmad@steadierfooting.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
